name: 💡 Feature request
description: Suggest an idea for Gahara
title: "💡 Feature: "
labels: ["feature"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this feature request!
  - type: dropdown
    id: type_of_feature
    attributes:
      label: Type of Feature
      multiple: true
      options:
        - 💡 Feature
        - 🐛 Fix
        - 📝 Documentation
        - 🎨 Style
        - 🔨 Refactor
        - ⚡️ Performance
        - ✅ Test
        - 🤖 Build
        - 🔁 CI/CD
        - 📦 Chore
        - ⏩ Revert
  - type: textarea
    id: current_behavior
    attributes:
      label: Current Behavior
      description: Is your feature request related to a problem? Please describe.
    validations:
      required: true
  - type: textarea
    id: suggested_solution
    attributes:
      label: Suggested solution
      description: Describe the solution you would like.
  - type: textarea
    id: additional_context
    attributes:
      label: Additional Context
      description: Add any other context about the problem or helpful links here
