// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateProjectWorkspace(arg1) {
  return window['go']['main']['App']['CreateProjectWorkspace'](arg1);
}

export function FilePicker() {
  return window['go']['main']['App']['FilePicker']();
}

export function GenerateThumbnail(arg1) {
  return window['go']['main']['App']['GenerateThumbnail'](arg1);
}

export function GenerateVideoConcatFile(arg1) {
  return window['go']['main']['App']['GenerateVideoConcatFile'](arg1);
}

export function GetThumbnail(arg1) {
  return window['go']['main']['App']['GetThumbnail'](arg1);
}

export function ReadGaharaWorkspace() {
  return window['go']['main']['App']['ReadGaharaWorkspace']();
}

export function ReadProjectWorkspace() {
  return window['go']['main']['App']['ReadProjectWorkspace']();
}

export function SetProjectDirectory(arg1) {
  return window['go']['main']['App']['SetProjectDirectory'](arg1);
}

export function TrimVideoInterval(arg1, arg2) {
  return window['go']['main']['App']['TrimVideoInterval'](arg1, arg2);
}
