// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddTrack() {
  return window['go']['main']['App']['AddTrack']();
}

export function AppMenu(arg1) {
  return window['go']['main']['App']['AppMenu'](arg1);
}

export function CreateProjectWorkspace(arg1) {
  return window['go']['main']['App']['CreateProjectWorkspace'](arg1);
}

export function DeleteProject(arg1) {
  return window['go']['main']['App']['DeleteProject'](arg1);
}

export function DeleteProjectFile(arg1) {
  return window['go']['main']['App']['DeleteProjectFile'](arg1);
}

export function DeleteRIDReferences(arg1) {
  return window['go']['main']['App']['DeleteRIDReferences'](arg1);
}

export function EnableExportMenus() {
  return window['go']['main']['App']['EnableExportMenus']();
}

export function EnableVideoMenus() {
  return window['go']['main']['App']['EnableVideoMenus']();
}

export function ExporterAudioNode() {
  return window['go']['main']['App']['ExporterAudioNode']();
}

export function ExporterPlaceholderNode() {
  return window['go']['main']['App']['ExporterPlaceholderNode']();
}

export function ExporterVideoNode() {
  return window['go']['main']['App']['ExporterVideoNode']();
}

export function FFmpegQuery(arg1, arg2) {
  return window['go']['main']['App']['FFmpegQuery'](arg1, arg2);
}

export function FilePicker() {
  return window['go']['main']['App']['FilePicker']();
}

export function GenerateThumbnail(arg1) {
  return window['go']['main']['App']['GenerateThumbnail'](arg1);
}

export function GetOutputFileSavePath() {
  return window['go']['main']['App']['GetOutputFileSavePath']();
}

export function GetProjectThumbnail(arg1) {
  return window['go']['main']['App']['GetProjectThumbnail'](arg1);
}

export function GetThumbnail(arg1) {
  return window['go']['main']['App']['GetThumbnail'](arg1);
}

export function GetTimeline() {
  return window['go']['main']['App']['GetTimeline']();
}

export function GetTrackDuration(arg1) {
  return window['go']['main']['App']['GetTrackDuration'](arg1);
}

export function InsertInterval(arg1, arg2, arg3, arg4, arg5, arg6, arg7) {
  return window['go']['main']['App']['InsertInterval'](arg1, arg2, arg3, arg4, arg5, arg6, arg7);
}

export function LoadProjectFiles() {
  return window['go']['main']['App']['LoadProjectFiles']();
}

export function LoadTimeline() {
  return window['go']['main']['App']['LoadTimeline']();
}

export function MarkAllLossless(arg1) {
  return window['go']['main']['App']['MarkAllLossless'](arg1);
}

export function OpenFile(arg1) {
  return window['go']['main']['App']['OpenFile'](arg1);
}

export function ReadGaharaWorkspace() {
  return window['go']['main']['App']['ReadGaharaWorkspace']();
}

export function ReadProjectWorkspace() {
  return window['go']['main']['App']['ReadProjectWorkspace']();
}

export function RemoveInterval(arg1, arg2) {
  return window['go']['main']['App']['RemoveInterval'](arg1, arg2);
}

export function RemoveTrack(arg1) {
  return window['go']['main']['App']['RemoveTrack'](arg1);
}

export function RenameVideoNode(arg1, arg2, arg3) {
  return window['go']['main']['App']['RenameVideoNode'](arg1, arg2, arg3);
}

export function ResetTimeline() {
  return window['go']['main']['App']['ResetTimeline']();
}

export function SaveProjectFiles(arg1) {
  return window['go']['main']['App']['SaveProjectFiles'](arg1);
}

export function SaveTimeline() {
  return window['go']['main']['App']['SaveTimeline']();
}

export function SetDefaultAppMenu() {
  return window['go']['main']['App']['SetDefaultAppMenu']();
}

export function SetProjectDirectory(arg1) {
  return window['go']['main']['App']['SetProjectDirectory'](arg1);
}

export function SplitInterval(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['SplitInterval'](arg1, arg2, arg3, arg4, arg5);
}

export function ToggleLossless(arg1, arg2) {
  return window['go']['main']['App']['ToggleLossless'](arg1, arg2);
}

export function UnmarkAllLossless(arg1) {
  return window['go']['main']['App']['UnmarkAllLossless'](arg1);
}
