// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';
import {video} from '../models';

export function CreateProjectWorkspace(arg1:string):Promise<string>;

export function FilePicker():Promise<main.Video>;

export function GenerateThumbnail(arg1:string):Promise<void>;

export function GenerateVideoConcatFile(arg1:Array<string>):Promise<void>;

export function GetThumbnail(arg1:string):Promise<void>;

export function GetTimeline():Promise<video.Timeline>;

export function InsertInterval(arg1:string,arg2:number,arg3:number,arg4:number):Promise<video.VideoNode>;

export function LoadTimeline():Promise<video.Timeline>;

export function ReadGaharaWorkspace():Promise<Array<string>>;

export function ReadProjectWorkspace():Promise<Array<main.Video>>;

export function RemoveInterval(arg1:number):Promise<void>;

export function ResetTimeline():Promise<void>;

export function SaveTimeline():Promise<void>;

export function SetProjectDirectory(arg1:string):Promise<void>;

export function SplitInterval(arg1:string,arg2:number,arg3:number,arg4:number):Promise<Array<video.VideoNode>>;

export function TrimVideoInterval(arg1:string,arg2:main.Interval):Promise<void>;
