// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateProjectWorkspace(arg1) {
  return window['go']['main']['App']['CreateProjectWorkspace'](arg1);
}

export function DeleteProjectFile(arg1) {
  return window['go']['main']['App']['DeleteProjectFile'](arg1);
}

export function DeleteRIDReferences(arg1) {
  return window['go']['main']['App']['DeleteRIDReferences'](arg1);
}

export function ExportVideo(arg1) {
  return window['go']['main']['App']['ExportVideo'](arg1);
}

export function FilePicker() {
  return window['go']['main']['App']['FilePicker']();
}

export function GenerateThumbnail(arg1) {
  return window['go']['main']['App']['GenerateThumbnail'](arg1);
}

export function GetOutputFileSavePath() {
  return window['go']['main']['App']['GetOutputFileSavePath']();
}

export function GetProjectThumbnail(arg1) {
  return window['go']['main']['App']['GetProjectThumbnail'](arg1);
}

export function GetThumbnail(arg1) {
  return window['go']['main']['App']['GetThumbnail'](arg1);
}

export function GetTimeline() {
  return window['go']['main']['App']['GetTimeline']();
}

export function GetTrackDuration() {
  return window['go']['main']['App']['GetTrackDuration']();
}

export function InsertInterval(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['InsertInterval'](arg1, arg2, arg3, arg4);
}

export function LoadTimeline() {
  return window['go']['main']['App']['LoadTimeline']();
}

export function ReadGaharaWorkspace() {
  return window['go']['main']['App']['ReadGaharaWorkspace']();
}

export function ReadProjectWorkspace() {
  return window['go']['main']['App']['ReadProjectWorkspace']();
}

export function RemoveInterval(arg1) {
  return window['go']['main']['App']['RemoveInterval'](arg1);
}

export function ResetTimeline() {
  return window['go']['main']['App']['ResetTimeline']();
}

export function SaveTimeline() {
  return window['go']['main']['App']['SaveTimeline']();
}

export function SetProjectDirectory(arg1) {
  return window['go']['main']['App']['SetProjectDirectory'](arg1);
}

export function SplitInterval(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['SplitInterval'](arg1, arg2, arg3, arg4);
}
